services:
  - type: web
    name: pwa-emergencias-backend
    env: node
    region: oregon
    plan: free
    buildCommand: "npm install"
    startCommand: "node server/server.js"
    envVars:
      - key: VAPID_PUBLIC_KEY
        sync: false
      - key: VAPID_PRIVATE_KEY
        sync: false
